#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nomad"
name = "Nomad"
description.en = "Simple and flexible workload orchestrator"
description.fr = "Orchestrateur de charge de travail simple et flexible"

version = "1.7.7~ynh2"

maintainers = []

[upstream]
license = "MPL-2.0"
website = "https://www.nomadproject.io"
admindoc = "https://www.nomadproject.io/docs"
code = "https://github.com/hashicorp/nomad"
cpe = "cpe:2.3:a:hashicorp:nomad"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "300M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.node_type]
    ask.en = "What kind of Nomad node you want to install?"
    type = "select"
    choices = ["server", "client"]
    default = "server"

    [install.bootstrap_expect]
    ask.en = "[Server only] How many server nodes to wait for before bootstrapping?"
    help.en = "For production, it's recommanded to have 3 to 5 server nodes."
    type = "select"
    choices = ["1", "3", "5", "7", "9"]
    default = "1"

    [install.retry_join]
    ask.en = "[Server only] What is the IP of another server to join?"
    type = "string"
    example = "192.168.1.100"
    optional = true

    [install.server_ip]
    ask.en = "[Client only] What is the IP of the Nomad server node?"
    type = "string"
    example = "192.168.1.100"
    optional = true

    [install.driver_lxc]
    ask.en = "[Client only] Do you want to install LXC driver?"
    help.en = "It will also install lxc."
    type = "boolean"
    default = true

[resources]
    [resources.sources.driver_lxc]
    url = "https://github.com/hashicorp/nomad-driver-lxc/archive/68239f4f639bde68e80616b7e931b8cc368969b0.tar.gz"
    sha256 = "50ddae947a189fefe0f6a5419d8f5ae749daa124f100b3ce900d83eab073c2ad"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["plugins"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 4646

    rpc.default = 4647
    rpc.fixed = true
    rpc.exposed = "TCP"
    serf.default = 4648
    serf.fixed = true
    serf.exposed = "TCP"

    [resources.apt]
    packages = []
    packages_from_raw_bash = """
        if [ "$node_type" == "client" ]; then
            if [ "$driver_lxc" -eq 1 ]; then
                echo pkg-config lxc-dev lxc lxc-templates
            fi
        fi
    """

    [resources.apt.extras.nomad]
    repo = "deb https://apt.releases.hashicorp.com bullseye main"
    key = "https://apt.releases.hashicorp.com/gpg"
    packages = ["nomad"]
