#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# Stopping Nomad
#=================================================
ynh_script_progression "Trying to stop gracefully $app..."

ynh_hide_warnings timeout 25 nomad node drain -self -enable -yes -deadline 20s

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

if [ "$node_type" == "client" ] && [ "$driver_lxc" -eq 1 ]; then
    client_lxc_bridge=$(ynh_app_setting_get --key=client_lxc_bridge)

    ynh_systemctl --service=lxc-net --action="stop"
    systemctl disable lxc-net --quiet
    ynh_safe_rm "/etc/default/lxc-net"
    ynh_safe_rm "/etc/lxc/default.conf"
    ynh_safe_rm "/etc/dnsmasq.d/lxd"
    systemctl restart dnsmasq
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================
if [ "$node_type" == "client" ] && [ "$driver_lxc" -eq 1 ]; then
    ynh_script_progression "Removing Go..."
    ynh_go_remove
fi

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove a directory securely
ynh_safe_rm "$config_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
