#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "$config_path"

chmod -R go-rwx,u-w "$config_path"
chown -R "$app:$app" "$config_path"

if [ "$node_type" == "client" ]; then
    if [ "$driver_lxc" -eq 1 ]; then
        client_lxc_main_iface=$(ip route | grep default | awk '{print $5;}')
        ynh_app_setting_set --key=client_lxc_main_iface --value="$client_lxc_main_iface"

        ynh_config_add --template="dnsmasq-lxd" --destination="/etc/dnsmasq.d/lxd"
        systemctl restart dnsmasq

        if ynh_in_ci_tests; then
            ynh_config_add --template="lxc-net" --destination="/etc/default/lxc-net"
        fi
        ynh_safe_rm "/etc/lxc/default.conf"
        ynh_config_add --template="default.conf" --destination="/etc/lxc/default.conf"
        systemctl enable lxc-net --quiet
        ynh_systemctl --service=lxc-net --action="restart" --wait_until="Finished LXC network bridge setup" --log_path="systemd"
    fi
fi

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --log="/var/log/$app/$app.log" --needs_exposed_ports "$port_rpc" "$port_serf"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"  --wait_until="Nomad agent started"

chmod -R go-rwx,u-w "$config_path"
chown -R "$app:$app" "$config_path"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
