#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_go
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
#REMOVEME? ynh_script_progression --message="Loading installation settings..." --weight=1

#REMOVEME? app=$YNH_APP_INSTANCE_NAME

#REMOVEME? domain=$(ynh_app_setting_get --app=$app --key=domain)
#REMOVEME? path=$(ynh_app_setting_get --app=$app --key=path)
#REMOVEME? config_path=$(ynh_app_setting_get --app=$app --key=config_path)
#REMOVEME? data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)
#REMOVEME? node_type=$(ynh_app_setting_get --app=$app --key=node_type)
#REMOVEME? bootstrap_expect=$(ynh_app_setting_get --app=$app --key=bootstrap_expect)
#REMOVEME? retry_join=$(ynh_app_setting_get --app=$app --key=retry_join)
#REMOVEME? server_ip=$(ynh_app_setting_get --app=$app --key=server_ip)
#REMOVEME? driver_lxc=$(ynh_app_setting_get --app=$app --key=driver_lxc)
#REMOVEME? http_port=$(ynh_app_setting_get --app=$app --key=http_port)
#REMOVEME? rpc_port=$(ynh_app_setting_get --app=$app --key=rpc_port)
#REMOVEME? serf_port=$(ynh_app_setting_get --app=$app --key=serf_port)

#=================================================
# CHECK VERSION
#=================================================
ynh_script_progression --message="Checking version..." --weight=1

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
#REMOVEME? ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=1

# Backup the current version of the app
#REMOVEME? ynh_backup_before_upgrade
#REMOVEME? ynh_clean_setup () {
	# Restore it if the upgrade fails
#REMOVEME? 	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
#REMOVEME? ynh_abort_if_errors

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# Cleaning legacy permissions
#REMOVEME? if ynh_legacy_permissions_exists; then
#REMOVEME? 	ynh_legacy_permissions_delete_all

	ynh_app_setting_delete --app=$app --key=is_public
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
#REMOVEME? ynh_script_progression --message="Making sure dedicated system user exists..." --weight=1

# Create a dedicated user (if not existing)
#REMOVEME? ynh_system_user_create --username=$app

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Upgrading dependencies..." --weight=1

if [ "$node_type" == "server" ]
then
#REMOVEME? 	pkg_dependencies="$pkg_dependencies $server_pkg_dependencies"
fi

if [ "$node_type" == "client" ]
then
	if [ $driver_lxc -eq 1 ]
	then
#REMOVEME? 		client_pkg_dependencies="$client_pkg_dependencies $client_lxc_pkg_dependencies"
		ynh_exec_warn_less ynh_install_go --go_version=$go_version
	fi	
#REMOVEME? 	pkg_dependencies="$pkg_dependencies $client_pkg_dependencies"
fi
#REMOVEME? ynh_install_app_dependencies $pkg_dependencies
#REMOVEME? ynh_install_extra_app_dependencies --repo="deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" --package="$extra_pkg_dependencies" --key="https://apt.releases.hashicorp.com/gpg"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# BUILD DRIVERS
#=================================================

if [ "$node_type" == "client" ]
then
	if [ $driver_lxc -eq 1 ]
	then
		ynh_script_progression --message="Building LXC driver..." --weight=1

		tempdir="$(mktemp -d)"
		ynh_setup_source --dest_dir="$tempdir" --source_id="driver-lxc"

		pushd $tempdir
#REMOVEME? 			install_dir=$tempdir
			ynh_use_go
			export GOPATH="$tempdir/go"
			export GOCACHE="$tempdir/.cache"
			ynh_exec_warn_less $ynh_go build
		popd

		mv -f $tempdir/nomad-driver-lxc $data_dir/plugins/nomad-driver-lxc

		ynh_secure_remove --file="$tempdir"
	fi
fi

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

mkdir -p $config_path
chmod 750 "$config_path"
chmod -R o-rwx "$config_path"
chown -R $app:$app "$config_path"

ynh_add_config --template="../conf/nomad.hcl" --destination="$config_path/nomad.hcl"
chmod 400 "$config_path/nomad.hcl"
chown $app:$app "$config_path/nomad.hcl"

if [ "$node_type" == "server" ]
then
	ynh_add_config --template="../conf/server.hcl" --destination="$config_path/server.hcl"
	chmod 400 "$config_path/server.hcl"
	chown $app:$app "$config_path/server.hcl"
fi

if [ "$node_type" == "client" ]
then
	ynh_add_config --template="../conf/client.hcl" --destination="$config_path/client.hcl"
	chmod 400 "$config_path/client.hcl"
	chown $app:$app "$config_path/client.hcl"
	
	if [ $driver_lxc -eq 1 ]
	then
		ynh_add_config --template="../conf/driver-lxc.hcl" --destination="$config_path/driver-lxc.hcl"
		chmod 400 "$config_path/driver-lxc.hcl"
		chown $app:$app "$config_path/driver-lxc.hcl"
	fi
fi

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=1

systemd_user=$app
if [ "$node_type" == "client" ]
then
	systemd_user="root"
fi
# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Upgrading logrotate configuration..." --weight=1

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate --non-append

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

needs_exposed_ports="$rpc_port"
if [ "$node_type" == "server" ]
then
	needs_exposed_ports="$serf_port $needs_exposed_ports"
fi
yunohost service add $app --log="/var/log/$app/$app.log" --needs_exposed_ports $needs_exposed_ports

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log" --line_match="Nomad agent started"

#=================================================
# RELOAD NGINX
#=================================================
#REMOVEME? ynh_script_progression --message="Reloading NGINX web server..." --weight=1

#REMOVEME? ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
